spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 100
      batch-size: 20000
      compression-type: gzip
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        linger.ms: 50
    consumer:
      group-id: em
      enable-auto-commit: false
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArraySerializer
      auto-offset-reset: lastest
    listener:
      concurrency: 5
      ack-mode: manual_immediate
      poll-timeout: 3000
      type: single
    retry:
      max-attempts: 10
      inital-interval: 1000
      multiplier: 2
      max-interval: 10000
    topics:
      em-topic: "auto.em.req"