// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResMessage.proto

package io.ensueno.sender.model;

public final class ResSendMessage {
  private ResSendMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.humuson.core.sender.model.ResMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 발송 요청한 Key 정보 Message.key
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    String getKey();
    /**
     * <pre>
     * 발송 요청한 Key 정보 Message.key
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <pre>
     * 발송 요청한 시간
     * </pre>
     *
     * <code>string reqSendTime = 2;</code>
     */
    String getReqSendTime();
    /**
     * <pre>
     * 발송 요청한 시간
     * </pre>
     *
     * <code>string reqSendTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getReqSendTimeBytes();

    /**
     * <pre>
     * 발송 시간
     * </pre>
     *
     * <code>string sentTime = 3;</code>
     */
    String getSentTime();
    /**
     * <pre>
     * 발송 시간
     * </pre>
     *
     * <code>string sentTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getSentTimeBytes();

    /**
     * <pre>
     * 발송 결과 수신 시간
     * </pre>
     *
     * <code>string resultTime = 4;</code>
     */
    String getResultTime();
    /**
     * <pre>
     * 발송 결과 수신 시간
     * </pre>
     *
     * <code>string resultTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getResultTimeBytes();

    /**
     * <pre>
     * 발송 결과 정보
     * </pre>
     *
     * <code>string code = 5;</code>
     */
    String getCode();
    /**
     * <pre>
     * 발송 결과 정보
     * </pre>
     *
     * <code>string code = 5;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <pre>
     * 발송 결과 메시지
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    String getMessage();
    /**
     * <pre>
     * 발송 결과 메시지
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 연동 에러 코드
     * </pre>
     *
     * <code>string transCode = 7;</code>
     */
    String getTransCode();
    /**
     * <pre>
     * 연동 에러 코드
     * </pre>
     *
     * <code>string transCode = 7;</code>
     */
    com.google.protobuf.ByteString
        getTransCodeBytes();

    /**
     * <pre>
     * retry 여부
     * </pre>
     *
     * <code>bool retry = 8;</code>
     */
    boolean getRetry();
  }
  /**
   * Protobuf type {@code com.humuson.core.sender.model.ResMessage}
   */
  public  static final class ResMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.humuson.core.sender.model.ResMessage)
      ResMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResMessage.newBuilder() to construct.
    private ResMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResMessage() {
      key_ = "";
      reqSendTime_ = "";
      sentTime_ = "";
      resultTime_ = "";
      code_ = "";
      message_ = "";
      transCode_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              reqSendTime_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              sentTime_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              resultTime_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              transCode_ = s;
              break;
            }
            case 64: {

              retry_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResSendMessage.internal_static_com_humuson_core_sender_model_ResMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResSendMessage.internal_static_com_humuson_core_sender_model_ResMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResMessage.class, Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile Object key_;
    /**
     * <pre>
     * 발송 요청한 Key 정보 Message.key
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 발송 요청한 Key 정보 Message.key
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQSENDTIME_FIELD_NUMBER = 2;
    private volatile Object reqSendTime_;
    /**
     * <pre>
     * 발송 요청한 시간
     * </pre>
     *
     * <code>string reqSendTime = 2;</code>
     */
    public String getReqSendTime() {
      Object ref = reqSendTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reqSendTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 발송 요청한 시간
     * </pre>
     *
     * <code>string reqSendTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReqSendTimeBytes() {
      Object ref = reqSendTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reqSendTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENTTIME_FIELD_NUMBER = 3;
    private volatile Object sentTime_;
    /**
     * <pre>
     * 발송 시간
     * </pre>
     *
     * <code>string sentTime = 3;</code>
     */
    public String getSentTime() {
      Object ref = sentTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sentTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 발송 시간
     * </pre>
     *
     * <code>string sentTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSentTimeBytes() {
      Object ref = sentTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sentTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTTIME_FIELD_NUMBER = 4;
    private volatile Object resultTime_;
    /**
     * <pre>
     * 발송 결과 수신 시간
     * </pre>
     *
     * <code>string resultTime = 4;</code>
     */
    public String getResultTime() {
      Object ref = resultTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resultTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 발송 결과 수신 시간
     * </pre>
     *
     * <code>string resultTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResultTimeBytes() {
      Object ref = resultTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resultTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 5;
    private volatile Object code_;
    /**
     * <pre>
     * 발송 결과 정보
     * </pre>
     *
     * <code>string code = 5;</code>
     */
    public String getCode() {
      Object ref = code_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 발송 결과 정보
     * </pre>
     *
     * <code>string code = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 6;
    private volatile Object message_;
    /**
     * <pre>
     * 발송 결과 메시지
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 발송 결과 메시지
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSCODE_FIELD_NUMBER = 7;
    private volatile Object transCode_;
    /**
     * <pre>
     * 연동 에러 코드
     * </pre>
     *
     * <code>string transCode = 7;</code>
     */
    public String getTransCode() {
      Object ref = transCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 연동 에러 코드
     * </pre>
     *
     * <code>string transCode = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTransCodeBytes() {
      Object ref = transCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        transCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETRY_FIELD_NUMBER = 8;
    private boolean retry_;
    /**
     * <pre>
     * retry 여부
     * </pre>
     *
     * <code>bool retry = 8;</code>
     */
    public boolean getRetry() {
      return retry_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!getReqSendTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reqSendTime_);
      }
      if (!getSentTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sentTime_);
      }
      if (!getResultTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, resultTime_);
      }
      if (!getCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, message_);
      }
      if (!getTransCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, transCode_);
      }
      if (retry_ != false) {
        output.writeBool(8, retry_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!getReqSendTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reqSendTime_);
      }
      if (!getSentTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sentTime_);
      }
      if (!getResultTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, resultTime_);
      }
      if (!getCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, message_);
      }
      if (!getTransCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, transCode_);
      }
      if (retry_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, retry_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResMessage)) {
        return super.equals(obj);
      }
      ResMessage other = (ResMessage) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getReqSendTime()
          .equals(other.getReqSendTime())) return false;
      if (!getSentTime()
          .equals(other.getSentTime())) return false;
      if (!getResultTime()
          .equals(other.getResultTime())) return false;
      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getTransCode()
          .equals(other.getTransCode())) return false;
      if (getRetry()
          != other.getRetry()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + REQSENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getReqSendTime().hashCode();
      hash = (37 * hash) + SENTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getSentTime().hashCode();
      hash = (37 * hash) + RESULTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getResultTime().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TRANSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getTransCode().hashCode();
      hash = (37 * hash) + RETRY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRetry());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.humuson.core.sender.model.ResMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.humuson.core.sender.model.ResMessage)
        ResMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResSendMessage.internal_static_com_humuson_core_sender_model_ResMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResSendMessage.internal_static_com_humuson_core_sender_model_ResMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResMessage.class, Builder.class);
      }

      // Construct using com.humuson.core.sender.model.ResSendMessage.ResMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        key_ = "";

        reqSendTime_ = "";

        sentTime_ = "";

        resultTime_ = "";

        code_ = "";

        message_ = "";

        transCode_ = "";

        retry_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResSendMessage.internal_static_com_humuson_core_sender_model_ResMessage_descriptor;
      }

      @Override
      public ResMessage getDefaultInstanceForType() {
        return ResMessage.getDefaultInstance();
      }

      @Override
      public ResMessage build() {
        ResMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ResMessage buildPartial() {
        ResMessage result = new ResMessage(this);
        result.key_ = key_;
        result.reqSendTime_ = reqSendTime_;
        result.sentTime_ = sentTime_;
        result.resultTime_ = resultTime_;
        result.code_ = code_;
        result.message_ = message_;
        result.transCode_ = transCode_;
        result.retry_ = retry_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResMessage) {
          return mergeFrom((ResMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResMessage other) {
        if (other == ResMessage.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getReqSendTime().isEmpty()) {
          reqSendTime_ = other.reqSendTime_;
          onChanged();
        }
        if (!other.getSentTime().isEmpty()) {
          sentTime_ = other.sentTime_;
          onChanged();
        }
        if (!other.getResultTime().isEmpty()) {
          resultTime_ = other.resultTime_;
          onChanged();
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getTransCode().isEmpty()) {
          transCode_ = other.transCode_;
          onChanged();
        }
        if (other.getRetry() != false) {
          setRetry(other.getRetry());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object key_ = "";
      /**
       * <pre>
       * 발송 요청한 Key 정보 Message.key
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 발송 요청한 Key 정보 Message.key
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 발송 요청한 Key 정보 Message.key
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 요청한 Key 정보 Message.key
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 요청한 Key 정보 Message.key
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private Object reqSendTime_ = "";
      /**
       * <pre>
       * 발송 요청한 시간
       * </pre>
       *
       * <code>string reqSendTime = 2;</code>
       */
      public String getReqSendTime() {
        Object ref = reqSendTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          reqSendTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 발송 요청한 시간
       * </pre>
       *
       * <code>string reqSendTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReqSendTimeBytes() {
        Object ref = reqSendTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reqSendTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 발송 요청한 시간
       * </pre>
       *
       * <code>string reqSendTime = 2;</code>
       */
      public Builder setReqSendTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqSendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 요청한 시간
       * </pre>
       *
       * <code>string reqSendTime = 2;</code>
       */
      public Builder clearReqSendTime() {
        
        reqSendTime_ = getDefaultInstance().getReqSendTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 요청한 시간
       * </pre>
       *
       * <code>string reqSendTime = 2;</code>
       */
      public Builder setReqSendTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqSendTime_ = value;
        onChanged();
        return this;
      }

      private Object sentTime_ = "";
      /**
       * <pre>
       * 발송 시간
       * </pre>
       *
       * <code>string sentTime = 3;</code>
       */
      public String getSentTime() {
        Object ref = sentTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sentTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 발송 시간
       * </pre>
       *
       * <code>string sentTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSentTimeBytes() {
        Object ref = sentTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sentTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 발송 시간
       * </pre>
       *
       * <code>string sentTime = 3;</code>
       */
      public Builder setSentTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 시간
       * </pre>
       *
       * <code>string sentTime = 3;</code>
       */
      public Builder clearSentTime() {
        
        sentTime_ = getDefaultInstance().getSentTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 시간
       * </pre>
       *
       * <code>string sentTime = 3;</code>
       */
      public Builder setSentTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sentTime_ = value;
        onChanged();
        return this;
      }

      private Object resultTime_ = "";
      /**
       * <pre>
       * 발송 결과 수신 시간
       * </pre>
       *
       * <code>string resultTime = 4;</code>
       */
      public String getResultTime() {
        Object ref = resultTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resultTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 발송 결과 수신 시간
       * </pre>
       *
       * <code>string resultTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResultTimeBytes() {
        Object ref = resultTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resultTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 발송 결과 수신 시간
       * </pre>
       *
       * <code>string resultTime = 4;</code>
       */
      public Builder setResultTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resultTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 결과 수신 시간
       * </pre>
       *
       * <code>string resultTime = 4;</code>
       */
      public Builder clearResultTime() {
        
        resultTime_ = getDefaultInstance().getResultTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 결과 수신 시간
       * </pre>
       *
       * <code>string resultTime = 4;</code>
       */
      public Builder setResultTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resultTime_ = value;
        onChanged();
        return this;
      }

      private Object code_ = "";
      /**
       * <pre>
       * 발송 결과 정보
       * </pre>
       *
       * <code>string code = 5;</code>
       */
      public String getCode() {
        Object ref = code_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 발송 결과 정보
       * </pre>
       *
       * <code>string code = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 발송 결과 정보
       * </pre>
       *
       * <code>string code = 5;</code>
       */
      public Builder setCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 결과 정보
       * </pre>
       *
       * <code>string code = 5;</code>
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 결과 정보
       * </pre>
       *
       * <code>string code = 5;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        code_ = value;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <pre>
       * 발송 결과 메시지
       * </pre>
       *
       * <code>string message = 6;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 발송 결과 메시지
       * </pre>
       *
       * <code>string message = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 발송 결과 메시지
       * </pre>
       *
       * <code>string message = 6;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 결과 메시지
       * </pre>
       *
       * <code>string message = 6;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 발송 결과 메시지
       * </pre>
       *
       * <code>string message = 6;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private Object transCode_ = "";
      /**
       * <pre>
       * 연동 에러 코드
       * </pre>
       *
       * <code>string transCode = 7;</code>
       */
      public String getTransCode() {
        Object ref = transCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          transCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 연동 에러 코드
       * </pre>
       *
       * <code>string transCode = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTransCodeBytes() {
        Object ref = transCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          transCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 연동 에러 코드
       * </pre>
       *
       * <code>string transCode = 7;</code>
       */
      public Builder setTransCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 연동 에러 코드
       * </pre>
       *
       * <code>string transCode = 7;</code>
       */
      public Builder clearTransCode() {
        
        transCode_ = getDefaultInstance().getTransCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 연동 에러 코드
       * </pre>
       *
       * <code>string transCode = 7;</code>
       */
      public Builder setTransCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transCode_ = value;
        onChanged();
        return this;
      }

      private boolean retry_ ;
      /**
       * <pre>
       * retry 여부
       * </pre>
       *
       * <code>bool retry = 8;</code>
       */
      public boolean getRetry() {
        return retry_;
      }
      /**
       * <pre>
       * retry 여부
       * </pre>
       *
       * <code>bool retry = 8;</code>
       */
      public Builder setRetry(boolean value) {
        
        retry_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * retry 여부
       * </pre>
       *
       * <code>bool retry = 8;</code>
       */
      public Builder clearRetry() {
        
        retry_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.humuson.core.sender.model.ResMessage)
    }

    // @@protoc_insertion_point(class_scope:com.humuson.core.sender.model.ResMessage)
    private static final ResMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResMessage();
    }

    public static ResMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResMessage>() {
      @Override
      public ResMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public ResMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_humuson_core_sender_model_ResMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_humuson_core_sender_model_ResMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020ResMessage.proto\022\035com.humuson.core.sen" +
      "der.model\"\225\001\n\nResMessage\022\013\n\003key\030\001 \001(\t\022\023\n" +
      "\013reqSendTime\030\002 \001(\t\022\020\n\010sentTime\030\003 \001(\t\022\022\n\n" +
      "resultTime\030\004 \001(\t\022\014\n\004code\030\005 \001(\t\022\017\n\007messag" +
      "e\030\006 \001(\t\022\021\n\ttransCode\030\007 \001(\t\022\r\n\005retry\030\010 \001(" +
      "\010B/\n\035com.humuson.core.sender.modelB\016ResS" +
      "endMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_humuson_core_sender_model_ResMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_humuson_core_sender_model_ResMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_humuson_core_sender_model_ResMessage_descriptor,
        new String[] { "Key", "ReqSendTime", "SentTime", "ResultTime", "Code", "Message", "TransCode", "Retry", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
